export enum HistoryType {
  PACKAGE_SEND = "PACKAGE PUT IN LOCKER",
  PACKAGE_RECEIVE_COURIER = "PACKAGE RETRIEVED BY COURIER",
  PACKAGE_RECEIVE_RECEIVER = "PACKAGE RETRIEVED BY RECEIVER",
  PACKAGE_IN_RECEIVER_LOCKER = "PACKAGE IN RECEIVER LOCKER",
}
