export const enum RecordType {
  PACKAGE_REGISTERED = "PACKAGE_REGISTERED",
  PACKAGE_PAID_FOR = "PACKAGE_PAID_FOR",
  PACKAGE_IN_SENDER_LOCKER = "PACKAGE_IN_SENDER_LOCKER",
  PACKAGE_IN_TRANSIT = "PAKCAGE_IN_TRANSIT",
  PACKAGE_IN_INTERMEDITE_LOCKER = "PACKAGE_IN_INTERMEDITE_LOCKER",
  PACKAGE_IN_RECEIVER_LOCKER = "PACKAGE_IN_RECEIVER_LOCKER",
  PACKAGE_IN_EXTERNAL_STORAGE = "PACKAGE_IN_EXTERNAL_STORAGE",
  PACKAGE_LOST = "PACKAGE_LOST",
  PACKAGE_DESTROYED = "PACKAGE_DESTROYED",
  PACKAGE_RECEIVED = "PACKAGE_RECEIVED",
}
